###sign up

POST http://localhost:3000/v1/api/shop/signup
content-Type: application/json

{
    "username": "Hien",
    "email": "hien@gmail.com",
    "mobile": "02432341231",
    "password": "123456"
}