###sign up

POST http://localhost:3000/v1/api/shop/signup
content-Type: application/json

{
    "username": "Hien",
    "email": "Hien@gmail.com",
    "mobile": "09442341231",
    "password": "123456"
}

###login

POST http://localhost:3000/v1/api/shop/login
content-Type: application/json

{
    "username": "Hien",
    "password": "123456"
}

###change-password
POST http://localhost:3000/v1/api/shop/change-password
Authorization: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDkxOGYwNGQzMTAyMWMyOTRjN2Y1NjIiLCJ1c2VybmFtZSI6IkJMVUUiLCJpYXQiOjE2ODc0MjkzMTIsImV4cCI6MTY4NzYwMjExMn0.bGQLH49xbucwvuvWNSsaWev4iuGzuyQk7zb4wgdm6sM"
x-client-id: "64918f04d31021c294c7f562"

{
    "password": "123456",
    "newPassword": "123",
    "verifyNewPassword": "123"
}